/**
 * AI Journey Summary - Quick Win Component
 *
 * Provides AI-powered narrative synthesis of user's journey
 * using the NarrativeSynthesisService and OpenRouter integration.
 */

import { useState, useEffect } from 'react';
import { Sparkles, Loader2 } from 'lucide-react';
import { NarrativeSynthesisService } from '../services/roe/NarrativeSynthesisService';

interface AIJourneySummaryProps {
  userId: string;
  timeframe?: 'daily' | 'weekly' | 'monthly';
}

export function AIJourneySummary({ userId, timeframe = 'weekly' }: AIJourneySummaryProps) {
  const [summary, setSummary] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadSummary();
  }, [userId, timeframe]);

  const loadSummary = async () => {
    setLoading(true);
    setError(null);

    try {
      const narrativeService = new NarrativeSynthesisService();
      const result = await narrativeService.synthesize(userId, timeframe);
      setSummary(result);
    } catch (err) {
      console.error('Failed to generate AI summary:', err);
      setError('Unable to generate summary. Please try again later.');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="bg-gradient-to-br from-purple-600/20 to-blue-600/20 border border-purple-500/30 rounded-lg p-6">
        <div className="flex items-center space-x-3 mb-4">
          <Sparkles className="w-6 h-6 text-purple-400 animate-pulse" />
          <h3 className="text-lg font-medium text-gray-200">AI Journey Summary</h3>
        </div>
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-8 h-8 text-purple-400 animate-spin" />
          <span className="ml-3 text-gray-400">Analyzing your journey...</span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-gradient-to-br from-purple-600/20 to-blue-600/20 border border-purple-500/30 rounded-lg p-6">
        <div className="flex items-center space-x-3 mb-4">
          <Sparkles className="w-6 h-6 text-purple-400" />
          <h3 className="text-lg font-medium text-gray-200">AI Journey Summary</h3>
        </div>
        <p className="text-red-400 text-sm">{error}</p>
        <button
          onClick={loadSummary}
          className="mt-4 text-sm text-purple-400 hover:text-purple-300 underline"
        >
          Try again
        </button>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-br from-purple-600/20 to-blue-600/20 border border-purple-500/30 rounded-lg p-6">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center space-x-3">
          <Sparkles className="w-6 h-6 text-purple-400" />
          <h3 className="text-lg font-medium text-gray-200">AI Journey Summary</h3>
        </div>
        <select
          value={timeframe}
          onChange={(e) => {
            // Trigger reload with new timeframe
            // In production, pass this to parent component
          }}
          className="bg-gray-800 border border-gray-700 rounded px-3 py-1 text-sm text-gray-300"
        >
          <option value="daily">Today</option>
          <option value="weekly">This Week</option>
          <option value="monthly">This Month</option>
        </select>
      </div>

      <div className="prose prose-invert prose-sm max-w-none">
        <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
          {summary || 'No data available for this timeframe. Continue your journey to see AI-generated insights.'}
        </p>
      </div>

      <div className="mt-4 pt-4 border-t border-gray-700">
        <p className="text-xs text-gray-500">
          Generated by AI • Reflects patterns in your recent journey
        </p>
      </div>
    </div>
  );
}
