/*
  # ROE Foundational Data: Monad Core & Emotion Map

  ## Overview
  Seeds the Reality Optimization Engine with archetypal consciousness patterns
  and emotion-frequency bidirectional mappings.

  ## Monad Core Archetypes
  Foundation patterns that represent fundamental consciousness states:
  - Void: Pre-manifest potential, pure awareness
  - Witness: Observing consciousness, detached presence
  - Seeker: Active inquiry, truth-orientation
  - Awakener: Emergence, recognition, insight
  - Integrator: Synthesis, embodiment, grounding
  - Expander: Transcendence, boundaries dissolving
  - Servant: Purpose-driven, service-oriented

  ## Emotion-Frequency Mappings
  Based on emotional scale research (Hawkins, Fredrickson, Porges polyvagal theory):
  - High frequency (0.7-1.0): Expansive states (peace, joy, love, gratitude)
  - Mid frequency (0.4-0.6): Neutral transition (contentment, acceptance, courage)
  - Low frequency (0.0-0.3): Contractive states (fear, shame, grief, anger)

  ## Integration with Navigator
  These archetypes map to Sacred Shifter's existing profiles:
  - Void/Witness → Observer profile
  - Seeker → Seeker profile
  - Awakener → Awakening profile
  - Integrator → Integrator profile
  - Expander → Expander profile
  - (Numb, Lost profiles handled through emotion map and regulation levels)

  ## Note on Embeddings
  Pattern embeddings will be generated by EmbeddingService and updated separately.
  Initial NULL values allow system to bootstrap without API dependency.
*/

-- ============================================================================
-- MONAD CORE: Archetypal Consciousness Patterns
-- ============================================================================

INSERT INTO public.monad_core (id, name, description, archetypal_essence, pattern_embedding, frequency_signature, metaphysical_properties)
VALUES
  (
    'monad_void',
    'The Void',
    'Pre-manifest potential and pure awareness. The ground of being before differentiation.',
    'emptiness, potential, silence, pre-emergence, formless, womb-space',
    NULL,  -- Will be populated by EmbeddingService
    '{"base_frequency": 0.95, "harmonics": [0.85, 0.90, 1.0], "resonance_bandwidth": 0.15}',
    '{"polarity": "neutral", "density": "ethereal", "orientation": "inward", "temporal_mode": "eternal_now"}'
  ),
  (
    'monad_witness',
    'The Witness',
    'Observing consciousness without attachment. Clear seeing, detached presence.',
    'observation, clarity, detachment, awareness, stillness, meta-cognition',
    NULL,
    '{"base_frequency": 0.88, "harmonics": [0.80, 0.85, 0.92], "resonance_bandwidth": 0.12}',
    '{"polarity": "neutral", "density": "light", "orientation": "receptive", "temporal_mode": "present"}'
  ),
  (
    'monad_seeker',
    'The Seeker',
    'Active inquiry and truth-orientation. Questioning, exploring, investigating reality.',
    'inquiry, curiosity, truth-seeking, exploration, investigation, questioning',
    NULL,
    '{"base_frequency": 0.72, "harmonics": [0.65, 0.70, 0.78], "resonance_bandwidth": 0.18}',
    '{"polarity": "expansive", "density": "dynamic", "orientation": "outward", "temporal_mode": "future-oriented"}'
  ),
  (
    'monad_awakener',
    'The Awakener',
    'Emergence of recognition and insight. Veils lifting, patterns revealed.',
    'recognition, insight, emergence, revelation, breakthrough, illumination',
    NULL,
    '{"base_frequency": 0.80, "harmonics": [0.75, 0.82, 0.88], "resonance_bandwidth": 0.20}',
    '{"polarity": "expansive", "density": "luminous", "orientation": "transformative", "temporal_mode": "threshold"}'
  ),
  (
    'monad_integrator',
    'The Integrator',
    'Synthesis and embodiment. Making wisdom flesh, grounding insight into action.',
    'integration, embodiment, synthesis, grounding, consolidation, manifestation',
    NULL,
    '{"base_frequency": 0.68, "harmonics": [0.60, 0.68, 0.75], "resonance_bandwidth": 0.16}',
    '{"polarity": "grounding", "density": "substantial", "orientation": "inward-outward", "temporal_mode": "cyclical"}'
  ),
  (
    'monad_expander',
    'The Expander',
    'Transcendence and boundary dissolution. Unity consciousness, oneness, cosmic perspective.',
    'transcendence, unity, oneness, expansion, boundlessness, cosmic-consciousness',
    NULL,
    '{"base_frequency": 0.92, "harmonics": [0.88, 0.95, 1.0], "resonance_bandwidth": 0.22}',
    '{"polarity": "expansive", "density": "infinite", "orientation": "omnidirectional", "temporal_mode": "timeless"}'
  ),
  (
    'monad_servant',
    'The Servant',
    'Purpose-driven action and service. Aligned will, sacred responsibility, duty of care.',
    'service, purpose, responsibility, alignment, duty, sacred-action',
    NULL,
    '{"base_frequency": 0.78, "harmonics": [0.72, 0.78, 0.84], "resonance_bandwidth": 0.14}',
    '{"polarity": "grounding", "density": "solid", "orientation": "outward", "temporal_mode": "purposeful"}'
  )
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- EMOTION MAP: Frequency-Emotion Bidirectional Mappings
-- ============================================================================

INSERT INTO public.emotion_map (id, emotion, frequency_value, polarity, regulation_correlation, somatic_markers)
VALUES
  -- High Frequency Expansive States (0.7-1.0)
  ('em_peace', 'peace', 0.95, 'expansive', 'high', '{"breath": "deep_slow", "heart_rate": "low_variability_high", "muscle_tone": "relaxed", "posture": "open"}'),
  ('em_joy', 'joy', 0.92, 'expansive', 'high', '{"breath": "full_rhythmic", "heart_rate": "elevated_coherent", "muscle_tone": "energized", "posture": "upright_open"}'),
  ('em_love', 'love', 0.90, 'expansive', 'high', '{"breath": "warm_flowing", "heart_rate": "coherent", "muscle_tone": "soft", "posture": "receptive_open"}'),
  ('em_gratitude', 'gratitude', 0.88, 'expansive', 'high', '{"breath": "expansive", "heart_rate": "coherent_elevated", "muscle_tone": "warm", "posture": "open_centered"}'),
  ('em_serenity', 'serenity', 0.85, 'expansive', 'high', '{"breath": "smooth_deep", "heart_rate": "low_coherent", "muscle_tone": "released", "posture": "settled"}'),
  ('em_awe', 'awe', 0.82, 'expansive', 'medium', '{"breath": "suspended_full", "heart_rate": "decelerated", "muscle_tone": "still", "posture": "receptive"}'),
  
  -- Mid-Range Neutral/Transition States (0.4-0.6)
  ('em_contentment', 'contentment', 0.72, 'neutral', 'high', '{"breath": "steady", "heart_rate": "baseline_coherent", "muscle_tone": "neutral", "posture": "balanced"}'),
  ('em_acceptance', 'acceptance', 0.68, 'neutral', 'high', '{"breath": "releasing", "heart_rate": "settling", "muscle_tone": "softening", "posture": "grounded"}'),
  ('em_curiosity', 'curiosity', 0.65, 'expansive', 'medium', '{"breath": "alert", "heart_rate": "slightly_elevated", "muscle_tone": "ready", "posture": "forward_engaged"}'),
  ('em_courage', 'courage', 0.62, 'expansive', 'medium', '{"breath": "strong_steady", "heart_rate": "elevated_controlled", "muscle_tone": "firm", "posture": "upright_grounded"}'),
  ('em_neutral', 'neutral', 0.50, 'neutral', 'medium', '{"breath": "automatic", "heart_rate": "baseline", "muscle_tone": "functional", "posture": "habitual"}'),
  ('em_boredom', 'boredom', 0.45, 'contractive', 'medium', '{"breath": "shallow_slow", "heart_rate": "low", "muscle_tone": "slack", "posture": "collapsed"}'),
  ('em_disappointment', 'disappointment', 0.40, 'contractive', 'medium', '{"breath": "sigh_deflated", "heart_rate": "dropping", "muscle_tone": "deflating", "posture": "slumped"}'),
  
  -- Low Frequency Contractive States (0.0-0.3)
  ('em_sadness', 'sadness', 0.35, 'contractive', 'low', '{"breath": "shallow_irregular", "heart_rate": "low_irregular", "muscle_tone": "heavy", "posture": "inward_collapsed"}'),
  ('em_anxiety', 'anxiety', 0.32, 'contractive', 'low', '{"breath": "shallow_rapid", "heart_rate": "elevated_chaotic", "muscle_tone": "tense", "posture": "braced_forward"}'),
  ('em_anger', 'anger', 0.28, 'contractive', 'low', '{"breath": "sharp_forceful", "heart_rate": "high_irregular", "muscle_tone": "rigid_explosive", "posture": "aggressive_forward"}'),
  ('em_fear', 'fear', 0.22, 'contractive', 'low', '{"breath": "held_shallow", "heart_rate": "racing_chaotic", "muscle_tone": "frozen_rigid", "posture": "protective_curled"}'),
  ('em_grief', 'grief', 0.18, 'contractive', 'low', '{"breath": "gasping_sobbing", "heart_rate": "irregular_weak", "muscle_tone": "collapsing", "posture": "fetal_protective"}'),
  ('em_shame', 'shame', 0.12, 'contractive', 'low', '{"breath": "shallow_held", "heart_rate": "dysregulated", "muscle_tone": "collapsed", "posture": "hidden_small"}'),
  ('em_numb', 'numb', 0.08, 'contractive', 'low', '{"breath": "barely_perceptible", "heart_rate": "dissociated", "muscle_tone": "deadened", "posture": "frozen_absent"}')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Verify monad core count
SELECT COUNT(*) as monad_count FROM public.monad_core;

-- Verify emotion map count and frequency distribution
SELECT 
  polarity,
  COUNT(*) as count,
  ROUND(AVG(frequency_value)::numeric, 2) as avg_frequency,
  ROUND(MIN(frequency_value)::numeric, 2) as min_frequency,
  ROUND(MAX(frequency_value)::numeric, 2) as max_frequency
FROM public.emotion_map
GROUP BY polarity
ORDER BY avg_frequency DESC;
